// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-meals.ts
import { createClient } from "npm:@supabase/supabase-js@^2.49.10";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.23.8";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_meals_default = defineTool({
  name: "list_meals",
  title: "List meals",
  description: "List meals in the signed-in user's current weekly meal plan. Optionally filter by day of the week.",
  inputSchema: {
    day: z.string().optional().describe("Optional day filter, e.g. 'Monday'. Omit to list every planned meal.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ day }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("meals").select("id, day, title, recipe_url, ingredients, dietary_preferences, notes, rating").eq("user_id", ctx.getUserId());
    if (day) query = query.eq("day", day);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { meals: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-weekly-plans.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.49.10";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.23.8";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_weekly_plans_default = defineTool2({
  name: "list_weekly_plans",
  title: "List saved weekly meal plans",
  description: "List the signed-in user's saved weekly meal plans. Optionally include the meals for each plan.",
  inputSchema: {
    includeMeals: z2.boolean().optional().describe("If true, include each plan's meals (day, title, ingredients).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ includeMeals }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data: plans, error } = await supabase.from("weekly_meal_plans").select("id, name, week_start_date, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    let result = plans ?? [];
    if (includeMeals && plans && plans.length > 0) {
      const { data: planMeals, error: mealsErr } = await supabase.from("weekly_plan_meals").select("plan_id, day, title, recipe_url, ingredients, dietary_preferences, notes, rating").in("plan_id", plans.map((p) => p.id));
      if (mealsErr) {
        return { content: [{ type: "text", text: mealsErr.message }], isError: true };
      }
      result = plans.map((p) => ({
        ...p,
        meals: (planMeals ?? []).filter((m) => m.plan_id === p.id)
      }));
    }
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: { plans: result }
    };
  }
});

// src/lib/mcp/tools/list-shopping-items.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.49.10";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.23.8";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_shopping_items_default = defineTool3({
  name: "list_shopping_items",
  title: "List shopping list items",
  description: "List items on the signed-in user's shopping list. Optionally include items already checked off.",
  inputSchema: {
    includeChecked: z3.boolean().optional().describe("If true, include items already marked as purchased. Defaults to false.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ includeChecked }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    let query = supabase.from("shopping_list_items").select("id, name, quantity, category, store, meal, checked").eq("user_id", ctx.getUserId());
    if (!includeChecked) query = query.eq("checked", false);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-shopping-item.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.49.10";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.23.8";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var add_shopping_item_default = defineTool4({
  name: "add_shopping_item",
  title: "Add shopping list item",
  description: "Add a manual item to the signed-in user's shopping list. Use for items not tied to a specific meal.",
  inputSchema: {
    name: z4.string().trim().min(1).describe("Item name, e.g. 'Milk'."),
    quantity: z4.string().trim().optional().describe("Quantity string, e.g. '2 gallons'."),
    category: z4.string().trim().optional().describe("Optional grocery category, e.g. 'dairy'."),
    store: z4.string().trim().optional().describe("Optional store name.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, quantity, category, store }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const { data, error } = await supabase.from("shopping_list_items").insert({
      user_id: ctx.getUserId(),
      name,
      quantity: quantity ?? "1",
      category: category ?? "other",
      store: store ?? "Unassigned",
      checked: false,
      is_manual: true
    }).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Added ${name} to your shopping list.` }],
      structuredContent: { item: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qtwwfuzqgwdrsrcnjclm";
var mcp_default = defineMcp({
  name: "meal-magic-mcp",
  title: "Meal Magic Shopper",
  version: "0.1.0",
  instructions: "Tools to read and modify the signed-in user's meal plans, saved weekly plans, and shopping list in Meal Magic Shopper.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_meals_default, list_weekly_plans_default, list_shopping_items_default, add_shopping_item_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
