// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtwwfuzqgwdrsrcnjclm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0d3dmdXpxZ3dkcnNyY25qY2xtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNDE3NjksImV4cCI6MjA2NDcxNzc2OX0.dVW9Oo7UAczVS09AHgUa7TX8co3qoPQBBEcg516k5i8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);